class constants(object):
    POPULATION = 300    

    DELTADISJOINT = 2.0
    DELTAWEIGHTS = .4
    DELTATHRESHOLD = 1.0

    STALESPECIES = 15

    MUTATECONNECTIONCHANCE = .25
    PERTURBCHANCE = 0.9
    CROSSOVERCHANCE = .75
    LINKMUTATIONCHANCE = 2.0
    NODEMUTATIONCHANCE = 0.5
    BIASMUTATIONCHANCE = .4
    STEPSIZE = .1
    
    DISABLEMUTATIONCHANCE = 0.4
    ENABLEMUTATIONCHANCE = .2

    TIMEOUTCONSTANT = 20

    MAXNODES = 100000
